name: Continous Integration

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Linter
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: ci
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3